"""New-request initialization, never applied to HITL or Executor resume.

Only receive starts a fresh Run. Completion must leave exact approvals, payloads,
observations and receipts available for a lost-response/projection recovery.
History, bounded last analysis and kernel choice have session lifetime instead.
"""


def new_request_defaults() -> dict:
    """Return fresh mutable containers for every Run-scoped channel."""
    return {
        "agent_runtime": "",
        "task_id": "",
        "public_run_id": "",
        "agent_run_id": "",
        "project_memory_result": None,
        "public_events": [],
        "routing_result": {},
        "final_response": None,
        "reviews": [],
        "plan_views": [],
        "asset_revision": "",
        "interaction_id": "",
        "interaction_revision": 1,
        "interaction_data": None,
        "review_action": None,
        "review_error": None,
        "approved_snapshot": None,
        "planning_revision_count": 0,
        "planning_feedback": [],
        "planning_previous_reviews": [],
        "planning_question": None,
        "planning_validation_error": None,
        "planning_route": "review",
        "planning_activity_id": "",
        "dataset_output_dir": "",
        "execution_id": None,
        "executor_version": 0,
        "executor_operation_number": 0,
        "executor_operation_id": "",
        "executor_wait_phase": "",
        "execution_command": {},
        "execution_phase": "",
        "submitted_steps": [],
        "next_step_sequence": 0,
        "completed_steps": [],
        "skipped_steps": [],
        "execution_decisions": {},
        "pending_decisions": [],
        "decision_review": None,
        "execution_review_validation_error": None,
        "observations": [],
        "execution_status": "",
        "execution_error": None,
        "analysis_failure": False,
        "terminal_event_seen": False,
        "report_status": "",
        "execution_snapshot": None,
        "failed_step_ids": [],
        "repair_attempts": 0,
        "repair_max_attempts": 0,
        "repair_authorized_level": 0,
        "repair_candidate": None,
        "repair_review": None,
        "repair_action": "",
        "repair_history": [],
        "repair_stop_reason": None,
        "repair_validation_error": None,
        "initial_request_receipt": None,
        "user_resume_receipt": None,
        "ew_pending": {},
        "ew_receipts": {},
        "ew_sequences": {},
    }
