"""Analysis resource access delegates to the unified Workflow package."""
from agent_service.agents.analysis.workflow.paths import (
    LEGACY_SKILL_PREFIX,
    LEGACY_TOOL_PREFIX,
    SKILL_SOURCE_PREFIXES,
    TOOL_SOURCE_PREFIXES,
    RELOCATED_SKILL_PREFIX,
    RELOCATED_TOOL_PREFIX,
    SKILL_INDEX_PATH,
    SKILL_SOURCE_PREFIX,
    SKILLS_ROOT,
    SOURCE_ROOT,
    TOOL_REGISTRY_PATH,
    TOOL_SOURCE_PREFIX,
    TOOLS_ROOT,
    WORKFLOW_ROOT,
    resolve_tool_source,
)

__all__ = [
    "LEGACY_SKILL_PREFIX", "LEGACY_TOOL_PREFIX",
    "SKILL_SOURCE_PREFIXES", "TOOL_SOURCE_PREFIXES",
    "RELOCATED_SKILL_PREFIX", "RELOCATED_TOOL_PREFIX", "SKILL_INDEX_PATH",
    "SKILL_SOURCE_PREFIX", "SKILLS_ROOT", "SOURCE_ROOT", "TOOL_REGISTRY_PATH",
    "TOOL_SOURCE_PREFIX", "TOOLS_ROOT", "WORKFLOW_ROOT", "resolve_tool_source",
]
