"""Initial chat CRUD schema baseline.

Revision ID: 20260821_0001
Revises:
Create Date: 2026-08-21
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260821_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    statements = (
        "CREATE TYPE delete_yn AS ENUM ('N', 'Y')",
        (
            "CREATE TYPE project_member_role AS ENUM ('owner', "
            "'editor', 'viewer')"
        ),
        (
            "CREATE TYPE message_type AS ENUM ('system', 'user', "
            "'assistant', "
            "'tool')"
        ),
        (
            "CREATE TYPE message_status AS ENUM ('pending', "
            "'streaming', 'completed', 'failed', "
            "'cancelled')"
        ),
        (
            "CREATE TYPE llm_run_status AS ENUM ('queued', 'running', "
            "'completed', 'failed', "
            "'cancelled')"
        ),
        (
            "CREATE TYPE agent_run_status AS ENUM ('pending', "
            "'running', 'interrupted', 'success', 'error', 'timeout', "
            "'canceled')"
        ),
        """CREATE TABLE users (
            user_id UUID PRIMARY KEY, user_name VARCHAR(100) NOT NULL,
            delete_yn delete_yn NOT NULL DEFAULT 'N', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ)""",
        """CREATE TABLE projects (
            project_id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
            project_name VARCHAR(200) NOT NULL, system_prompt TEXT NOT NULL DEFAULT '',
            prompt_version INTEGER NOT NULL DEFAULT 1, is_default BOOLEAN NOT NULL DEFAULT false,
            delete_yn delete_yn NOT NULL DEFAULT 'N', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
            CONSTRAINT uq_projects_project_owner UNIQUE (project_id, user_id))""",
        """CREATE TABLE project_members (
            project_id UUID NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
            user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            member_role project_member_role NOT NULL DEFAULT 'owner', joined_dt TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (project_id, user_id))""",
        """CREATE TABLE sessions (
            session_id UUID PRIMARY KEY, project_id UUID NOT NULL REFERENCES projects(project_id) ON DELETE RESTRICT,
            user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
            session_name VARCHAR(300) NOT NULL DEFAULT '새 대화', current_leaf_message_id UUID,
            default_model_provider VARCHAR(50), default_model_name VARCHAR(100), settings JSONB NOT NULL DEFAULT '{}'::jsonb,
            delete_yn delete_yn NOT NULL DEFAULT 'N', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ)""",
        """CREATE TABLE messages (
            message_id UUID PRIMARY KEY, session_id UUID NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
            parent_message_id UUID, message_type message_type NOT NULL, content JSONB NOT NULL DEFAULT '[]'::jsonb,
            content_text TEXT NOT NULL DEFAULT '', message_status message_status NOT NULL DEFAULT 'completed',
            client_request_id UUID, error_code VARCHAR(100), error_message TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
            sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
            delete_yn delete_yn NOT NULL DEFAULT 'N', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
            CONSTRAINT uq_messages_message_session UNIQUE (message_id, session_id),
            CONSTRAINT fk_messages_parent_same_session FOREIGN KEY (parent_message_id, session_id)
                REFERENCES messages (message_id, session_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_messages_not_self_parent CHECK (parent_message_id IS NULL OR parent_message_id <> message_id))""",
        """ALTER TABLE sessions ADD CONSTRAINT fk_sessions_current_leaf
            FOREIGN KEY (current_leaf_message_id, session_id) REFERENCES messages (message_id, session_id)
            ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED""",
        """CREATE TABLE llm_runs (
            run_id UUID PRIMARY KEY, session_id UUID NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
            trigger_message_id UUID NOT NULL REFERENCES messages(message_id) ON DELETE RESTRICT,
            assistant_message_id UUID REFERENCES messages(message_id) ON DELETE CASCADE,
            provider VARCHAR(50) NOT NULL, model_name VARCHAR(100) NOT NULL, temperature NUMERIC(4,3),
            max_output_tokens INTEGER, project_prompt_version INTEGER NOT NULL, system_prompt_snapshot TEXT NOT NULL,
            request_messages_snapshot JSONB NOT NULL, raw_response JSONB NOT NULL DEFAULT '{}'::jsonb,
            status llm_run_status NOT NULL DEFAULT 'queued', prompt_tokens INTEGER, completion_tokens INTEGER,
            total_tokens INTEGER, latency_ms INTEGER, finish_reason VARCHAR(100), error_code VARCHAR(100), error_message TEXT,
            attempt_count INTEGER NOT NULL DEFAULT 0, retry_count INTEGER NOT NULL DEFAULT 0,
            max_retries INTEGER NOT NULL DEFAULT 5, attempt_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
            queued_at TIMESTAMPTZ NOT NULL DEFAULT now(), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_llm_runs_trigger_message UNIQUE (trigger_message_id),
            CONSTRAINT uq_llm_runs_assistant_message UNIQUE (assistant_message_id))""",
        """CREATE TABLE agent_runs (
            run_id UUID PRIMARY KEY, session_id UUID NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
            trigger_message_id UUID REFERENCES messages(message_id) ON DELETE RESTRICT,
            agent_message_id UUID REFERENCES messages(message_id) ON DELETE SET NULL,
            interpreted_message_id UUID REFERENCES messages(message_id) ON DELETE SET NULL,
            workflow_stage VARCHAR(30) NOT NULL DEFAULT 'prepared', request_payload JSONB, agent_response JSONB,
            redis_key VARCHAR(500), redis_result JSONB, status agent_run_status NOT NULL DEFAULT 'pending',
            input JSONB, command JSONB, metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
            idempotency_key VARCHAR(255) NOT NULL, multitask_strategy VARCHAR(30) NOT NULL DEFAULT 'reject',
            stream_mode JSONB NOT NULL DEFAULT '[]'::jsonb, stream_resumable BOOLEAN NOT NULL DEFAULT true,
            on_disconnect VARCHAR(30) NOT NULL DEFAULT 'continue', interrupt JSONB, failure JSONB, cancel_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, dispatched_at TIMESTAMPTZ,
            agent_completed_at TIMESTAMPTZ, redis_received_at TIMESTAMPTZ, interpreted_at TIMESTAMPTZ)""",
        "CREATE INDEX ix_projects_user_id ON projects (user_id)",
        "CREATE INDEX ix_sessions_project_id ON sessions (project_id)",
        "CREATE INDEX ix_sessions_user_id ON sessions (user_id)",
        "CREATE INDEX ix_messages_session_id ON messages (session_id)",
        (
            "CREATE INDEX ix_messages_parent_message_id ON messages "
            "(parent_message_id)"
        ),
        (
            "CREATE UNIQUE INDEX uq_messages_client_request ON messages "
            "(session_id, client_request_id) WHERE client_request_id IS "
            "NOT NULL"
        ),
        "CREATE INDEX ix_llm_runs_session_id ON llm_runs (session_id)",
        "CREATE INDEX ix_agent_runs_session_id ON agent_runs (session_id)",
        (
            "CREATE INDEX ix_agent_runs_trigger_message_id ON "
            "agent_runs (trigger_message_id)"
        ),
        (
            "CREATE INDEX ix_agent_runs_workflow_stage ON agent_runs "
            "(workflow_stage)"
        ),
        "CREATE INDEX ix_agent_runs_redis_key ON agent_runs (redis_key)",
    )
    for statement in statements:
        op.execute(statement)


def downgrade() -> None:
    op.execute(
        "ALTER TABLE sessions DROP CONSTRAINT IF EXISTS "
        "fk_sessions_current_leaf"
    )
    for table in (
        "agent_runs",
        "llm_runs",
        "messages",
        "sessions",
        "project_members",
        "projects",
        "users",
    ):
        op.execute(f"DROP TABLE {table}")
    for enum_name in (
        "agent_run_status",
        "llm_run_status",
        "message_status",
        "message_type",
        "project_member_role",
        "delete_yn",
    ):
        op.execute(f"DROP TYPE {enum_name}")
