apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-prj-03-0042-v2-api-basic-dev
  labels:
    app: gaia-prj-03-0042-v2-api-basic-dev
    prjId: gaia-prj-03-0042-v2
    rscId: gaia-prj-03-0042-v2-api
    target: basic
    env: dev
    locId: hy-ic-k8s-app-d01
spec:
  replicas: '[설정 값 변경 불가]'
  selector:
    matchLabels:
      app: gaia-prj-03-0042-v2-api-basic-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gaia-prj-03-0042-v2-api-basic-dev
        prjId: gaia-prj-03-0042-v2
        rscId: gaia-prj-03-0042-v2-api
        target: basic
        env: dev
        locId: hy-ic-k8s-app-d01
        prjCat: GaiA
        svcType: app
        appType: GAIA-FRAMEWORK
        logging: project
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /service/metrics
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: gaia-prj-03-0042-v2-api-basic-dev
        image: '[설정 값 변경 불가]'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: '[설정 값 변경 불가]'
        - name: REDIS_URL
          value: '[설정 값 변경 불가]'
        - name: MODEL_API_KEY
          value: '[설정 값 변경 불가]'
        - name: CHECKPOINT_DB_URI
          value: '[설정 값 변경 불가]'
        - name: PYTHONUTF8
          value: '1'
        - name: PYTHONIOENCODING
          value: utf-8
        - name: PYTHONPATH
          value: /app/src:/app
        - name: EW_DATABASE_URL
          value: '[설정 값 변경 불가]'
        - name: APP_ENV
          value: dev
        livenessProbe:
          httpGet:
            path: /service/live
            port: 5000
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: '[설정 값 변경 불가]'
            memory: '[설정 값 변경 불가]'
          requests:
            cpu: '[설정 값 변경 불가]'
            memory: '[설정 값 변경 불가]'
        command:
        - python
        - app.py
        volumeMounts:
        - name: timezone-config
          mountPath: /etc/localtime
        readinessProbe:
          httpGet:
            path: /service/ready
            port: 5000
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /service/ready
            port: 5000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 60
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      serviceAccountName: default
      restartPolicy: Always
      terminationGracePeriodSeconds: 70
---
apiVersion: v1
kind: Service
metadata:
  name: gaia-prj-03-0042-v2-api-basic-dev-svc
  labels:
    app: gaia-prj-03-0042-v2-api-basic-dev
    prjId: gaia-prj-03-0042-v2
    rscId: gaia-prj-03-0042-v2-api
    target: basic
    env: dev
    locId: hy-koic-k8s-app-d01
spec:
  selector:
    app: gaia-prj-03-0042-v2-api-basic-dev
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gaia-prj-03-0042-v2-api-basic-dev-ingress
  labels:
    app: gaia-prj-03-0042-v2-api-basic-dev
    prjId: gaia-prj-03-0042-v2
    rscId: gaia-prj-03-0042-v2-api
    target: basic
    env: dev
    locId: hy-koic-k8s-app-d01
spec:
  rules:
  - host: gaia-prj-03-0042-v2-api-basic-dev.api.hcpnd01.skhynix.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: gaia-prj-03-0042-v2-api-basic-dev-svc
            port:
              number: 5000
        pathType: Prefix
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gaia-prj-03-0042-v2-api-basic-dev-hpa
  labels:
    app: gaia-prj-03-0042-v2-api-basic-dev
    prjId: gaia-prj-03-0042-v2
    rscId: gaia-prj-03-0042-v2-api
    target: basic
    env: dev
    locId: hy-koic-k8s-app-d01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gaia-prj-03-0042-v2-api-basic-dev
  minReplicas: '[설정 값 변경 불가]'
  maxReplicas: '[설정 값 변경 불가]'
  targetCPUUtilizationPercentage: '[설정 값 변경 불가]'
